package com.sparrowwallet.lark;

import com.sparrowwallet.drongo.Network;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Runs the shared adversarial cases against the real session and reports what
 * this implementation actually does with each.
 *
 * The cases are generated by vectors/build_negatives.py from the captured
 * testnet4 transcript, so the semantic case is identical across transport
 * profiles and only the carriage differs.
 *
 * This test deliberately does NOT assert that every case is rejected. Some are
 * expected to be accepted today, because the coordinator does not yet enforce a
 * response allowlist, and one is arguably not a failure for this profile at all
 * (see below). Asserting a uniform rejection would either fail for reasons
 * already known, or tempt someone to weaken the case set until it passed.
 * Instead the security-critical subset is asserted hard, and the rest is
 * printed so the gap is visible and quotable rather than implied.
 */
public class AntiExfilNegativesTest {

    private static final Path NEGATIVES = Paths.get("vectors/negatives");
    private static Network originalNetwork;

    /**
     * Cases where acceptance would be a security failure, not a gap. These are
     * asserted. Everything else is reported.
     *
     * unrelated-valid-signature is the regression case for the exact-signature
     * binding: before that fix, a valid signature under another key could
     * satisfy the ECDSA half while the sign-to-contract half was checked
     * against a different signature.
     */
    private static final List<String> MUST_REJECT = List.of(
            "changed-signing-context",
            "cross-key-signature",
            "unrelated-valid-signature");

    @BeforeAll
    public static void useTestnet() {
        originalNetwork = Network.get();
        Network.set(Network.TESTNET);
    }

    @AfterAll
    public static void restoreNetwork() {
        Network.set(originalNetwork);
    }

    @Test
    public void testSharedNegatives() throws Exception {
        assertTrue(Files.isDirectory(NEGATIVES),
                "run vectors/build_negatives.py first - " + NEGATIVES.toAbsolutePath() + " is missing");

        Map<String, String> outcome = new LinkedHashMap<>();
        List<String> unexpectedlyAccepted = new ArrayList<>();

        List<Path> cases = new ArrayList<>(Files.list(NEGATIVES)
                .filter(p -> p.toString().endsWith(".psbt.b64")).sorted().toList());
        assertTrue(!cases.isEmpty(), "no negative fixtures found");

        for(Path path : cases) {
            String id = path.getFileName().toString().replace(".psbt.b64", "");
            byte[] response = Base64.getDecoder().decode(Files.readString(path).trim());

            String result;
            try {
                freshSession().verifyAndExtract(response);
                result = "ACCEPTED";
                if(MUST_REJECT.contains(id)) {
                    unexpectedlyAccepted.add(id);
                }
            } catch(SecurityException e) {
                result = "rejected (SecurityException)";
            } catch(IllegalStateException e) {
                result = "rejected (IllegalStateException)";
            } catch(Exception e) {
                result = "rejected (" + e.getClass().getSimpleName() + ")";
            }
            outcome.put(id, result);
        }

        System.out.println("\nShared adversarial cases against this coordinator:");
        for(Map.Entry<String, String> e : outcome.entrySet()) {
            String flag = MUST_REJECT.contains(e.getKey()) ? " [must reject]" : "";
            System.out.printf("  %-28s %s%s%n", e.getKey(), e.getValue(), flag);
        }
        System.out.println();

        if(!unexpectedlyAccepted.isEmpty()) {
            fail("security-critical cases were accepted: " + unexpectedlyAccepted);
        }
    }

    /**
     * A session carried through to the point of accepting a signed response,
     * using the entropy the recorded run used, so each negative is judged
     * against the same state the real ceremony reached.
     */
    private AntiExfilSession freshSession() throws Exception {
        byte[] entropy = AntiExfilSessionTest.hex(AntiExfilSessionTest.RECORDED_HOST_ENTROPY);
        AntiExfilSession session = new AntiExfilSession(
                AntiExfilSessionTest.b64(AntiExfilSessionTest.ROUND1_OUT),
                Map.of(0, List.of(AntiExfilSessionTest.hex(AntiExfilSessionTest.SIGNER_PUBKEY))),
                (index, pubkey) -> entropy);
        session.buildRound1();
        session.acceptRound1Reply(AntiExfilSessionTest.b64(AntiExfilSessionTest.ROUND1_REPLY));
        session.buildRound2();
        return session;
    }
}
