package com.sparrowwallet.lark;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Base64;
import java.util.List;
import java.util.Map;

/**
 * Writes all four stage artifacts of the recorded testnet4 ceremony to disk.
 *
 * Three of the four came off hardware and are stored verbatim as fixtures. M3
 * never was: it is a coordinator output, so no device ever sent it back. It is
 * captured here by replaying the session with the entropy that run actually
 * used, which reproduces the exact bytes the device received, because
 * buildRound2() is a deterministic function of the base PSBT, the recorded
 * opening and that entropy.
 *
 * That is a stronger claim than "reconstructed", and it is checkable rather
 * than asserted: the hardware signature in M4 verifies against the opening and
 * entropy carried in this M3, which it could not do had the device received
 * anything else.
 *
 * Run: java com.sparrowwallet.lark.AntiExfilTranscriptExport [output-directory]
 */
public final class AntiExfilTranscriptExport {

    private static final String DEFAULT_DIR = "vectors/transcript";

    private AntiExfilTranscriptExport() {}

    public static void main(String[] args) throws Exception {
        Path dir = Paths.get(args.length > 0 ? args[0] : DEFAULT_DIR);
        Files.createDirectories(dir);

        byte[] entropy = AntiExfilSessionTest.hex(AntiExfilSessionTest.RECORDED_HOST_ENTROPY);
        byte[] pubkey = AntiExfilSessionTest.hex(AntiExfilSessionTest.SIGNER_PUBKEY);

        AntiExfilSession session = new AntiExfilSession(
                AntiExfilSessionTest.b64(AntiExfilSessionTest.ROUND1_OUT),
                Map.of(0, List.of(pubkey)),
                (index, key) -> entropy);

        byte[] m1 = session.buildRound1();
        session.acceptRound1Reply(AntiExfilSessionTest.b64(AntiExfilSessionTest.ROUND1_REPLY));
        byte[] m3 = session.buildRound2();

        // Verification must still pass on the replayed session, otherwise the
        // captured M3 is not the one that produced the recorded M4.
        session.verifyAndExtract(AntiExfilSessionTest.b64(AntiExfilSessionTest.ROUND2_REPLY));

        write(dir.resolve("M1-coordinator-to-signer.psbt.b64"), m1);
        writeRaw(dir.resolve("M2-signer-to-coordinator.psbt.b64"), AntiExfilSessionTest.ROUND1_REPLY);
        write(dir.resolve("M3-coordinator-to-signer.psbt.b64"), m3);
        writeRaw(dir.resolve("M4-signer-to-coordinator.psbt.b64"), AntiExfilSessionTest.ROUND2_REPLY);

        boolean m1Matches = AntiExfilSessionTest.ROUND1_OUT.equals(base64(m1));
        System.out.println("Wrote four stage artifacts to " + dir.toAbsolutePath());
        System.out.println("M1 regenerated byte-identical to the recorded fixture: " + m1Matches);
        System.out.println("M3 captured (" + m3.length + " bytes); verification of the recorded M4 passed "
                + "against this M3, so it is the message the device received.");

        if(!m1Matches) {
            throw new IllegalStateException("M1 replay does not reproduce the recorded fixture - "
                    + "the capture cannot be trusted");
        }
    }

    private static void write(Path path, byte[] psbt) throws Exception {
        Files.writeString(path, base64(psbt) + "\n", StandardCharsets.UTF_8);
    }

    private static void writeRaw(Path path, String b64) throws Exception {
        Files.writeString(path, b64 + "\n", StandardCharsets.UTF_8);
    }

    private static String base64(byte[] b) {
        return Base64.getEncoder().encodeToString(b);
    }
}
